### ISSUE TITLE
index number of images selected for evaluation

### ISSUE THREAD

**Issue by yarqian** [chxy95/HDRUNet#2]
Many thanks for your work. Would you mind provide the index number of images selected for evaluation? 
Many thanks

**Comment by chxy95** [comment]
@yarqian hello,  the file that recorded index number of the validation data is uploaded:  
https://github.com/chxy95/HDRUNet/blob/main/random_valid.txt

**Comment by yarqian** [comment]
Many thanks for your help. I will close this issue.
