### ISSUE TITLE
[About sub images]

### ISSUE THREAD

**Issue by CaptainEven** [chxy95/HDRUNet#9]
May i ask why need to crop sub-imgs to train? Will the crop-sub_img operation run each epoch during training?

**Comment by chxy95** [comment]
@CaptainEven Cropping is a common operation of **preprocessing** in low-level vision task. You can also read the whole image instead of sub-images, but it will greatly increase the cost of reading.

**Comment by CaptainEven** [comment]
@chxy95 Thank you for your explanation!
Is random cropping operation be done each epoch for better exploration of the training dataset?

**Comment by chxy95** [comment]
@CaptainEven Cropping sub-images is for fast reading, thus this operation is performed before training.
Cropping patches randomly in fixed patch size to train is a common operation in low-level vision task, e.g. SR, denoising.
Of course the second cropping operation is done in each iteration. It is a important part of the data-loader script.

**Comment by CaptainEven** [comment]
@chxy95 I got it! Thanks!
